# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161213_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
